### ISSUE TITLE
Aborted(code dumped) with MNIST examples

### ISSUE THREAD

**Issue by astrung** [mila-udem/fuel#269] opened 2015-11-05 03:28 UTC
I have downloaded MNIST data(4 files)-and when i try to build with fuel-convert : i get this error:
python: malloc.c:3695: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
Aborted (core dumped).
How to fix it?i have try to re-download data

**Comment by rizar** [comment] 2015-11-05 13:55
We would need versions of Python, numpy, h5py, fuel and maybe something
else to try to help you.

**Comment by astrung** [comment] 2015-11-06 01:00
Python 2.7.6
Numpy 1.9
h5cc:4.8.4
Fuel:clone from github

**Comment by dwf** [comment] 2015-11-06 01:09
Platform? 32 or 64 bit?

**Comment by astrung** [comment] 2015-11-06 01:31
Ubuntu-32 bit(I installed in 2 computer:1 Centos and 1 ubuntu)-it appear on ubuntu

**Comment by astrung** [comment] 2015-11-14 03:45
When i run command:
f.attrs['split'] = H5PYDataset.create_split_array(split_dict) 
by this tutorial:https://fuel.readthedocs.org/en/latest/h5py_dataset.html
I still get same error.I think we have some problems with hdf5 and h5cc installing.But now i can not uninstall hdf5 so can i reinstall hdf5 and using with new install directory?

**Comment by dwf** [comment] 2015-11-14 04:15
We know that Linux 32-bit doesn't work for some reason. Closing this ticket as a duplicate of #216

**Closed by dwf** 2015-11-14 04:15 UTC

**Comment by astrung** [comment] 2015-11-14 04:35
So we have any solution for 32-bit system??or reinstall 64bit OS???

**Comment by dwf** [comment] 2015-11-14 05:00
We'd like to fix it, but it's unfortunately not a high priority for us as
we are all on 64-bit systems. It also might be beyond our ability to fix,
as in it may be a bug in h5py or even hdf5.

@lamblin have you had any luck investigating this 32-bit issue?

**Comment by lamblin** [comment] 2015-11-16 23:41
I did not investigate much, but no luck for the moment :-/
