### ISSUE TITLE
image.MinimumImageDimensions, I

### ISSUE THREAD

**Issue by DanlanChen** [mila-udem/fuel#312] opened 2016-02-11 20:57 UTC
https://github.com/mila-udem/fuel/blob/master/fuel/transformers/image.py
Can anyone tell me how to use image.MinimumImageDimensions, I tried 
stream = DataStream.default_stream(
   train,
   iteration_scheme=ShuffledScheme(train.num_examples, 128))
scaled_stream = MinimumImageDimensions(stream,(64*64))
cropped_stream = RandomFixedSizeCrop(
    scaled_stream, (32, 32), which_sources=('image_features',))
flattened_stream = Flatten(
    cropped_stream, which_sources=('image_features',))
but got this error:
Blocks will attempt to run `on_error` extensions, potentially saving data, before exiting and reraising the error. Note that the usual `after_training` extensions will *not* be run. The original error will be re-raised and also stored in the training log. Press CTRL + C to halt Blocks immediately.
Traceback (most recent call last):
  File "start.py", line 61, in <module>
    main_loop.run()
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/blocks/main_loop.py", line 197, in run
    reraise_as(e)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/blocks/utils/__init__.py", line 258, in reraise_as
    six.reraise(type(new_exc), new_exc, orig_exc_traceback)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/blocks/main_loop.py", line 183, in run
    while self._run_epoch():
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/blocks/main_loop.py", line 232, in _run_epoch
    while self._run_iteration():
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/blocks/main_loop.py", line 245, in _run_iteration
    batch = next(self.epoch_iterator)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/six.py", line 535, in next
    return type(self).__next__(self)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/iterator.py", line 32, in __next__
    data = self.data_stream.get_data()
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/transformers/__init__.py", line 138, in get_data
    data = next(self.child_epoch_iterator)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/six.py", line 535, in next
    return type(self).__next__(self)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/iterator.py", line 32, in __next__
    data = self.data_stream.get_data()
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/transformers/__init__.py", line 138, in get_data
    data = next(self.child_epoch_iterator)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/six.py", line 535, in next
    return type(self).__next__(self)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/iterator.py", line 32, in __next__
    data = self.data_stream.get_data()
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/transformers/__init__.py", line 151, in get_data
    return self.transform_batch(data)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/transformers/__init__.py", line 289, in transform_batch
    data=batch, method=self.transform_source_batch)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/transformers/__init__.py", line 250, in _apply_sourcewise_transformation
    data[i] = method(data[i], source_name)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/transformers/image.py", line 143, in transform_source_batch
    return [self._example_transform(im, source_name) for im in batch]
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/transformers/image.py", line 154, in _example_transform
    min_height, min_width = self.minimum_shape
TypeError: 'int' object is not iterable

**Comment by vdumoulin** [comment] 2016-02-11 21:03
I gather you mistyped and wrote `(6464)` instead of `(64, 64)` as `MinimumImageDimensions`'s second argument.

**Comment by DanlanChen** [comment] 2016-02-11 21:13
Thank you! And after I fixed it, I get this error: 	AxisLabelsMismatchError: MinimumImageDimensions expected axis labels ('batch', 'channel', 'height', 'width'), got (u'batch', u'index') instead
What does this batch channel should be.

**Comment by vdumoulin** [comment] 2016-02-11 21:23
By default, `MinimumImageDimensions` applies to all data sources. You'll have to restrict its application to the images only by passing the `which_sources=('image_features',)` keyword argument to the constructor, like you're doing in the `RandomFixedSizeCrop` constructor.

**Comment by DanlanChen** [comment] 2016-02-11 22:12
Thanks !
But I get this error below after 7th iteration:
[ift6ed05@hades fuel_data]$ python start.py 

-------------------------------------------------------------------------------
BEFORE FIRST EPOCH
-------------------------------------------------------------------------------
Training status:
	 batch_interrupt_received: False
	 epoch_interrupt_received: False
	 epoch_started: True
	 epochs_done: 0
	 iterations_done: 0
	 received_first_batch: False
	 resumed_from: None
	 training_started: True
Log records from the iteration 0:


-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Training status:
	 batch_interrupt_received: False
	 epoch_interrupt_received: False
	 epoch_started: True
	 epochs_done: 0
	 iterations_done: 1
	 received_first_batch: True
	 resumed_from: None
	 training_started: True
Log records from the iteration 1:
	 loss: 0.69348008545


-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Training status:
	 batch_interrupt_received: False
	 epoch_interrupt_received: False
	 epoch_started: True
	 epochs_done: 0
	 iterations_done: 2
	 received_first_batch: True
	 resumed_from: None
	 training_started: True
Log records from the iteration 2:
	 loss: 0.702513794837


-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Training status:
	 batch_interrupt_received: False
	 epoch_interrupt_received: False
	 epoch_started: True
	 epochs_done: 0
	 iterations_done: 3
	 received_first_batch: True
	 resumed_from: None
	 training_started: True
Log records from the iteration 3:
	 loss: 0.987339014662


-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Training status:
	 batch_interrupt_received: False
	 epoch_interrupt_received: False
	 epoch_started: True
	 epochs_done: 0
	 iterations_done: 4
	 received_first_batch: True
	 resumed_from: None
	 training_started: True
Log records from the iteration 4:
	 loss: 3.63817668021


-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Training status:
	 batch_interrupt_received: False
	 epoch_interrupt_received: False
	 epoch_started: True
	 epochs_done: 0
	 iterations_done: 5
	 received_first_batch: True
	 resumed_from: None
	 training_started: True
Log records from the iteration 5:
	 loss: 2.30525004483


-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Training status:
	 batch_interrupt_received: False
	 epoch_interrupt_received: False
	 epoch_started: True
	 epochs_done: 0
	 iterations_done: 6
	 received_first_batch: True
	 resumed_from: None
	 training_started: True
Log records from the iteration 6:
	 loss: 2.45784084603


-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Training status:
	 batch_interrupt_received: False
	 epoch_interrupt_received: False
	 epoch_started: True
	 epochs_done: 0
	 iterations_done: 7
	 received_first_batch: True
	 resumed_from: None
	 training_started: True
Log records from the iteration 7:
	 loss: 1.9683148743

ERROR:blocks.main_loop:Error occured during training.

Blocks will attempt to run `on_error` extensions, potentially saving data, before exiting and reraising the error. Note that the usual `after_training` extensions will *not* be run. The original error will be re-raised and also stored in the training log. Press CTRL + C to halt Blocks immediately.
Traceback (most recent call last):
  File "start.py", line 62, in <module>
    main_loop.run()
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/blocks/main_loop.py", line 197, in run
    reraise_as(e)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/blocks/utils/__init__.py", line 258, in reraise_as
    six.reraise(type(new_exc), new_exc, orig_exc_traceback)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/blocks/main_loop.py", line 183, in run
    while self._run_epoch():
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/blocks/main_loop.py", line 232, in _run_epoch
    while self._run_iteration():
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/blocks/main_loop.py", line 245, in _run_iteration
    batch = next(self.epoch_iterator)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/six.py", line 535, in next
    return type(self).__next__(self)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/iterator.py", line 32, in __next__
    data = self.data_stream.get_data()
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/transformers/__init__.py", line 138, in get_data
    data = next(self.child_epoch_iterator)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/six.py", line 535, in next
    return type(self).__next__(self)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/iterator.py", line 32, in __next__
    data = self.data_stream.get_data()
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/transformers/__init__.py", line 138, in get_data
    data = next(self.child_epoch_iterator)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/six.py", line 535, in next
    return type(self).__next__(self)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/iterator.py", line 32, in __next__
    data = self.data_stream.get_data()
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/transformers/__init__.py", line 151, in get_data
    return self.transform_batch(data)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/transformers/__init__.py", line 289, in transform_batch
    data=batch, method=self.transform_source_batch)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/transformers/__init__.py", line 250, in _apply_sourcewise_transformation
    data[i] = method(data[i], source_name)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/transformers/image.py", line 143, in transform_source_batch
    return [self._example_transform(im, source_name) for im in batch]
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/transformers/image.py", line 164, in _example_transform
    im = Image.fromarray(im)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 2153, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type

Original exception:
	TypeError: Cannot handle this data type

**Comment by vdumoulin** [comment] 2016-02-11 22:20
What dataset are you using?

**Comment by DanlanChen** [comment] 2016-02-11 22:26
dog and cat.

**Comment by bartvm** [comment] 2016-02-11 22:33
Do you know how to use `pdb` for debugging? If not, try and look up a tutorial for it, it'll be very useful when developing in Python. Try it by starting your program with `python -m pdb start.py` and then pressing `c` (continue) to start. Once it crashes, use `u` to go up until you get to line 164 in `image.py`s `_example_transform` function. Have a look at what the `im` variable is (what is its shape, its values, etc.) to try and figure out why Pillow says that it cannot read it.

**Comment by vdumoulin** [comment] 2016-02-12 00:49
The following minimal code reproduces the issue:

``` python
from fuel.datasets import DogsVsCats
from fuel.schemes import ShuffledScheme
from fuel.streams import DataStream
from fuel.transformers.image import MinimumImageDimensions


if __name__ == "__main__":
    train = DogsVsCats(('train',))
    stream = MinimumImageDimensions(
        DataStream.default_stream(
            train, iteration_scheme=ShuffledScheme(train.num_examples, 128)),
        (64, 64),
        which_sources=('image_features',))
    for batch in stream.get_epoch_iterator():
        pass
```

It appears that the rescaling introduced by `DogsVsCats`'s default transformers doesn't play very nice with PIL. Switching to the usual `DataStream()` constructor call solves the issue, because it leaves data as [0, 255] `uint8` values which PIL handles nicely.

I'd recommend applying resizing and cropping first and _then_ scaling through the `ScaleAndShift` transformer.

**Comment by vdumoulin** [comment] 2016-02-15 17:38
I'll go ahead and close the issue. Feel free to re-open or write to the [mailing list](https://groups.google.com/forum/#!forum/fuel-users) if you have more questions.

**Closed by vdumoulin** 2016-02-15 17:38 UTC

**Comment by DanlanChen** [comment] 2016-02-15 23:21
Hi, @bartvm 
Here is im after 7th iteration:(Pdb) im
array([[[ 0.04705882,  0.02352941,  0.03137255],
        [ 0.07058824,  0.04705882,  0.05490196],
        [ 0.09411765,  0.07058824,  0.07843137],
        ..., 
        [ 0.35294118,  0.29411765,  0.30588235],
        [ 0.31372549,  0.31372549,  0.34509804],
        [ 0.29019608,  0.29019608,  0.32156863]],

       [[ 0.03137255,  0.00784314,  0.01568627],
        [ 0.08627451,  0.0627451 ,  0.07058824],
        [ 0.1372549 ,  0.12156863,  0.1254902 ],
        ..., 
        [ 0.28235294,  0.22352941,  0.23529412],
        [ 0.26666667,  0.2627451 ,  0.28627451],
        [ 0.23921569,  0.23529412,  0.25882353]],

       [[ 0.02352941,  0.00784314,  0.01176471],
        [ 0.10588235,  0.09019608,  0.09411765],
        [ 0.18431373,  0.16862745,  0.17254902],
        ..., 
        [ 0.45490196,  0.40784314,  0.41568627],
        [ 0.3372549 ,  0.32941176,  0.34901961],
        [ 0.30980392,  0.30196078,  0.32156863]],

       ..., 
       [[ 0.1254902 ,  0.01960784,  0.07843137],
        [ 0.30980392,  0.20392157,  0.2627451 ],
        [ 0.53333333,  0.41176471,  0.4745098 ],
        ..., 
        [ 0.30196078,  0.16078431,  0.17647059],
        [ 0.23921569,  0.1372549 ,  0.14117647],
        [ 0.21176471,  0.10980392,  0.11372549]],

       [[ 0.12941176,  0.07058824,  0.09803922],
        [ 0.4       ,  0.33333333,  0.36470588],
        [ 0.45882353,  0.38039216,  0.41568627],
        ..., 
        [ 0.23529412,  0.12941176,  0.15686275],
        [ 0.22352941,  0.11764706,  0.1372549 ],
        [ 0.2       ,  0.09411765,  0.11372549]],

       [[ 0.12941176,  0.07058824,  0.09803922],
        [ 0.4       ,  0.33333333,  0.36470588],
        [ 0.45882353,  0.38039216,  0.41568627],
        ..., 
        [ 0.23529412,  0.12941176,  0.15686275],
        [ 0.22745098,  0.12156863,  0.14117647],
        [ 0.2       ,  0.09411765,  0.11372549]]])
(Pdb) im.shape
(50, 66, 3)

**Comment by DanlanChen** [comment] 2016-02-15 23:22
Hi,@vdumoulin, I do not understand the difference between resizing  and reshape. In my opinion, they are the same.

**Comment by bartvm** [comment] 2016-02-15 23:49
@vdumoulin isn't talking about scaling the image, he's talking about scaling the range of the values.

The images are originally loaded as RGB images. That means that each value is an integer in the range `[0, 255]`. Before feeding the image to the network we usually *scale* the values by turning them into floating point numbers and dividing them by 255 so that we get values in the range `[0, 1]` (easier to train). This is what `DataStream.default_stream` does.

The problem is that `MinimumImageDimensions` uses PIL to read the image and resize it. PIL wants the images to be in their original RGB format, with values in the range `[0, 255]`. But you had already scaled the values to `[0, 1]`, so PIL complains.

The way to fix this is by not using `default_stream`, and instead loading the original images (`DataStream(dataset, iteration_scheme=...)`), then applying `MinimumImageDimensions` and only then applying the `ScaleAndShift` transformer to divide the values by 255.
